title: Relaxing Knowledge
author: Lewis MK
email: elmurimi@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This blog will share funny, insightful, and memorable facts on a weekly basis. You can depend on us for exciting and relaxing content.

# social links
twitter_username: KotheLewis # DO NOT include the @ character, or else the build will fail!
github_username:  LewisMK # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
